[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.5.0"
wit-bindgen-rt = "0.26.0"
chrono = "0.4.33"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:demo"

[package.metadata.component.dependencies]
